services:
  - type: cron
    name: sharepoint-reminder-cron
    env: python
    schedule: "0 9 * * *" # Run daily at 9:00 AM UTC (adjust as needed)
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: SHAREPOINT_SHARED_URL
        value: "https://r3factoryae-my.sharepoint.com/:x:/g/personal/technical_r3factory_ae/EX11P9jpMAZOnNlg6hhYGUUBNo56OzdCIhmi5yAdw1MFQQ?e=NUcdQE"
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: EMAIL_USERNAME
        value: hussain.f.kagi@gmail.com
      - key: EMAIL_PASSWORD
        value: "aclb kyal bhsz epzy"
      - key: RECIPIENT_EMAILS
        value: "hussain.f.kagi@gmail.com,mukul.anand@r3factory.ae,rajesh.r@r3factory.ae" # Add your actual second recipient email here
